# Generated by Django 5.2.4 on 2025-07-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('client', models.CharField(blank=True, default='', max_length=200, verbose_name='クライアント')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('active', '進行中'), ('paused', '一時停止'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='planning', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予算')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('case_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('active', '進行中'), ('completed', '完了'), ('on_hold', '保留'), ('cancelled', 'キャンセル'), ('inspection_pending', '検収待ち')], default='planning', max_length=20, verbose_name='ステータス')),
                ('case_classification', models.CharField(choices=[('development', '開発'), ('maintenance', '保守'), ('consulting', 'コンサルティング'), ('support', 'サポート'), ('other', 'その他')], default='development', max_length=20, verbose_name='案件分類')),
                ('estimate_date', models.DateField(blank=True, null=True, verbose_name='見積日')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='受注日')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='終了日（予定）')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='終了日実績')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='検収日')),
                ('budget_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='使用可能金額（税別）')),
                ('billing_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='請求金額（税別）')),
                ('outsourcing_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='外注費（税別）')),
                ('estimated_workdays', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='見積工数（人日）')),
                ('used_workdays', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='使用工数（人日）')),
                ('newbie_workdays', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='新入社員使用工数（人日）')),
                ('billing_destination', models.CharField(blank=True, max_length=200, verbose_name='請求先')),
                ('billing_contact', models.CharField(blank=True, max_length=100, verbose_name='請求先担当者')),
                ('mub_manager', models.CharField(blank=True, max_length=100, verbose_name='MUB担当者')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '案件詳細',
                'verbose_name_plural': '案件詳細',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '中'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=20, verbose_name='優先度')),
                ('status', models.CharField(choices=[('open', 'オープン'), ('in_progress', '進行中'), ('review', 'レビュー中'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
                'ordering': ['-created_at'],
            },
        ),
    ]
