# Generated by Django 5.2.4 on 2025-07-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('estimate_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outsourcing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_workdays', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('used_workdays', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('newbie_workdays', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remaining_workdays', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_destination', models.CharField(blank=True, max_length=100)),
                ('billing_contact', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('mub_manager', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='departments.department')),
            ],
        ),
    ]
