# Generated by Django 5.2.4 on 2025-07-19 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('code', models.CharField(help_text='例: PROJ-2025-001', max_length=50, unique=True, verbose_name='プロジェクトコード')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('client', models.CharField(blank=True, max_length=200, null=True, verbose_name='クライアント')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('active', '進行中'), ('on_hold', '保留中'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='planning', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=20, verbose_name='優先度')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始予定日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了予定日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='実際の開始日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='実際の終了日')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='予算（円）')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='見積工数（時間）')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.department', verbose_name='担当部署')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='プロジェクトマネージャー')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='例: 開発者、テスター、デザイナー', max_length=100, null=True, verbose_name='役割')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='時間単価（円）')),
                ('join_date', models.DateField(verbose_name='参加日')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='離脱日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'プロジェクトメンバー',
                'verbose_name_plural': 'プロジェクトメンバー',
                'ordering': ['join_date'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='フェーズ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('start_date', models.DateField(verbose_name='開始予定日')),
                ('end_date', models.DateField(verbose_name='終了予定日')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='見積工数（時間）')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='順序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'プロジェクトフェーズ',
                'verbose_name_plural': 'プロジェクトフェーズ',
                'ordering': ['order', 'start_date'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
