# Generated by Django 5.2.4 on 2025-07-19 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Cost Master',
                'verbose_name_plural': 'Cost Masters',
            },
        ),
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='時間単価（円）')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rates', to='users.department', verbose_name='部署')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rates', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'コスト単価',
                'verbose_name_plural': 'コスト単価',
                'ordering': ['-effective_from'],
            },
        ),
    ]
