# Generated by Django 5.2.4 on 2025-07-21 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_level', models.CharField(choices=[('junior', '新入社員'), ('mid', '中堅社員'), ('senior', '上級社員'), ('manager', '管理職')], default='mid', max_length=50, verbose_name='社員レベル')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='原価（万円/月）')),
                ('monthly_billing', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='請求単価（万円/月）')),
                ('hourly_cost', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='時間単価原価（円/時間）')),
                ('hourly_billing', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='時間単価請求（円/時間）')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='有効開始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コストマスター',
                'verbose_name_plural': 'コストマスター',
                'ordering': ['-effective_from'],
            },
        ),
    ]
