# Generated by Django 5.2.4 on 2025-07-18 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costmaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='costmaster',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='costmaster',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='costmaster',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
