# Generated by Django 5.2.4 on 2025-07-19 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='工数（時間）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作業内容')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='残業時間')),
                ('year_month', models.CharField(help_text='YYYY-MM形式', max_length=7, verbose_name='年月')),
                ('is_billable', models.BooleanField(default=True, verbose_name='請求対象')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='users.department', verbose_name='部署')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='projects.projectphase', verbose_name='フェーズ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='projects.project', verbose_name='プロジェクト')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='users.section', verbose_name='課')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '工数',
                'verbose_name_plural': '工数',
                'ordering': ['-work_date'],
                'unique_together': {('user', 'project', 'work_date')},
            },
        ),
    ]
