# Generated by Django 5.2.4 on 2025-07-19 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY-MM形式', max_length=7, verbose_name='年月')),
                ('day_01', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='1日')),
                ('day_02', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='2日')),
                ('day_03', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='3日')),
                ('day_04', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='4日')),
                ('day_05', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='5日')),
                ('day_06', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='6日')),
                ('day_07', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='7日')),
                ('day_08', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='8日')),
                ('day_09', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='9日')),
                ('day_10', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='10日')),
                ('day_11', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='11日')),
                ('day_12', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='12日')),
                ('day_13', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='13日')),
                ('day_14', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='14日')),
                ('day_15', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='15日')),
                ('day_16', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='16日')),
                ('day_17', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='17日')),
                ('day_18', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='18日')),
                ('day_19', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='19日')),
                ('day_20', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='20日')),
                ('day_21', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='21日')),
                ('day_22', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='22日')),
                ('day_23', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='23日')),
                ('day_24', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='24日')),
                ('day_25', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='25日')),
                ('day_26', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='26日')),
                ('day_27', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='27日')),
                ('day_28', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='28日')),
                ('day_29', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='29日')),
                ('day_30', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='30日')),
                ('day_31', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='31日')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='月間合計時間')),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='月間合計人日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='users.department', verbose_name='部署')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='projects.project', verbose_name='案件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '工数',
                'verbose_name_plural': '工数',
                'ordering': ['-year_month', 'department', 'user', 'project'],
                'unique_together': {('user', 'project', 'year_month')},
            },
        ),
    ]
