# Generated by Django 5.2.4 on 2025-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='レポート名')),
                ('report_type', models.CharField(choices=[('monthly', '月次レポート'), ('project', 'プロジェクトレポート'), ('user', 'ユーザーレポート'), ('department', '部署レポート')], max_length=20, verbose_name='レポートタイプ')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='フォーマット')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='ファイルパス')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='ファイルサイズ（バイト）')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'レポートエクスポート',
                'verbose_name_plural': 'レポートエクスポート',
                'ordering': ['-created_at'],
            },
        ),
    ]
